#!/usr/bin/env python 
# -*- coding: utf-8 -*-"
"""
CBT (Core Brim Tech) - Denial of Service Toolkit - 2024 - by MOMODU KAMARA-KOLLEH

You should have received a copy of the GNU General Public License along
with CBT; if not, write to the Free Software Foundation, Inc., 51
Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""
from core.main import UFONet

if __name__ == "__main__":
    app = UFONet()
    options = app.create_options()
    if options:
        app.run()
