#!/usr/bin/env python3 
# -*- coding: utf-8 -*-"
"""
This file is part of the CBT (Core Brim Tech) project, https://www.corebrimtech.com

Copyright (c) 2024 | MOMODU KAMARA-KOLLEH

Automated Report Generation
"""
import json, time, os
from datetime import datetime

class ReportGenerator(object):
    """Generate professional penetration testing reports"""
    
    def __init__(self, ufonet):
        self.ufonet = ufonet
    
    def generate_html_report(self, attack_data, output_file='report.html'):
        """Generate HTML report"""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>CBT Attack Report - {datetime.now().strftime('%Y-%m-%d')}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #333; }}
        h2 {{ color: #666; border-bottom: 2px solid #333; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background-color: #4CAF50; color: white; }}
        tr:nth-child(even) {{ background-color: #f2f2f2; }}
        .vulnerability {{ background-color: #ffebee; }}
        .success {{ color: green; }}
        .failure {{ color: red; }}
    </style>
</head>
<body>
    <h1>CBT (Core Brim Tech) Attack Report</h1>
    <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    
    <h2>Executive Summary</h2>
    <p>This report details the security assessment performed using CBT toolkit.</p>
    
    <h2>Target Information</h2>
    <table>
        <tr><th>Target</th><td>{attack_data.get('target', 'N/A')}</td></tr>
        <tr><th>Attack Duration</th><td>{attack_data.get('duration', 'N/A')}</td></tr>
        <tr><th>Total Attacks</th><td>{attack_data.get('total_attacks', 0)}</td></tr>
        <tr><th>Success Rate</th><td>{attack_data.get('success_rate', 0)*100:.1f}%</td></tr>
    </table>
    
    <h2>Attack Vectors</h2>
    <table>
        <tr>
            <th>Attack Type</th>
            <th>Rounds</th>
            <th>Success</th>
            <th>Status</th>
        </tr>
"""
        
        for attack in attack_data.get('attacks', []):
            status_class = 'success' if attack.get('success', False) else 'failure'
            html += f"""
        <tr>
            <td>{attack.get('type', 'N/A')}</td>
            <td>{attack.get('rounds', 0)}</td>
            <td>{'Yes' if attack.get('success', False) else 'No'}</td>
            <td class="{status_class}">{'Success' if attack.get('success', False) else 'Failed'}</td>
        </tr>
"""
        
        html += """
    </table>
    
    <h2>Vulnerabilities Found</h2>
    <table>
        <tr>
            <th>Vulnerability</th>
            <th>Severity</th>
            <th>Description</th>
        </tr>
"""
        
        for vuln in attack_data.get('vulnerabilities', []):
            html += f"""
        <tr class="vulnerability">
            <td>{vuln.get('name', 'N/A')}</td>
            <td>{vuln.get('severity', 'Medium')}</td>
            <td>{vuln.get('description', 'N/A')}</td>
        </tr>
"""
        
        html += """
    </table>
    
    <h2>Recommendations</h2>
    <ul>
        <li>Implement rate limiting</li>
        <li>Deploy WAF protection</li>
        <li>Monitor for DDoS attacks</li>
        <li>Implement proper authentication</li>
        <li>Regular security audits</li>
    </ul>
    
    <h2>Compliance</h2>
    <p>This assessment was performed in accordance with:</p>
    <ul>
        <li>OWASP Testing Guide</li>
        <li>NIST Cybersecurity Framework</li>
        <li>Authorized testing scope</li>
    </ul>
    
    <footer>
        <p><em>Generated by CBT (Core Brim Tech) - https://www.corebrimtech.com</em></p>
    </footer>
</body>
</html>
"""
        
        with open(output_file, 'w') as f:
            f.write(html)
        
        print(f"[Info] [AI] [Report] HTML report generated: {output_file}")
        return output_file
    
    def generate_json_report(self, attack_data, output_file='report.json'):
        """Generate JSON report"""
        report = {
            'metadata': {
                'generated': datetime.now().isoformat(),
                'tool': 'CBT (Core Brim Tech)',
                'version': '1.0'
            },
            'attack_data': attack_data
        }
        
        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2)
        
        print(f"[Info] [AI] [Report] JSON report generated: {output_file}")
        return output_file
    
    def generate_markdown_report(self, attack_data, output_file='report.md'):
        """Generate Markdown report"""
        md = f"""# CBT Attack Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Executive Summary

This report details the security assessment performed using CBT toolkit.

## Target Information

- **Target:** {attack_data.get('target', 'N/A')}
- **Duration:** {attack_data.get('duration', 'N/A')}
- **Total Attacks:** {attack_data.get('total_attacks', 0)}
- **Success Rate:** {attack_data.get('success_rate', 0)*100:.1f}%

## Attack Vectors

| Attack Type | Rounds | Success | Status |
|------------|--------|---------|--------|
"""
        
        for attack in attack_data.get('attacks', []):
            status = '✅ Success' if attack.get('success', False) else '❌ Failed'
            md += f"| {attack.get('type', 'N/A')} | {attack.get('rounds', 0)} | {'Yes' if attack.get('success', False) else 'No'} | {status} |\n"
        
        md += """
## Vulnerabilities Found

"""
        
        for vuln in attack_data.get('vulnerabilities', []):
            md += f"### {vuln.get('name', 'N/A')}\n"
            md += f"- **Severity:** {vuln.get('severity', 'Medium')}\n"
            md += f"- **Description:** {vuln.get('description', 'N/A')}\n\n"
        
        md += """
## Recommendations

1. Implement rate limiting
2. Deploy WAF protection
3. Monitor for DDoS attacks
4. Implement proper authentication
5. Regular security audits

## Compliance

This assessment was performed in accordance with:
- OWASP Testing Guide
- NIST Cybersecurity Framework
- Authorized testing scope

---
*Generated by CBT (Core Brim Tech) - https://www.corebrimtech.com*
"""
        
        with open(output_file, 'w') as f:
            f.write(md)
        
        print(f"[Info] [AI] [Report] Markdown report generated: {output_file}")
        return output_file
